### ISSUE TITLE
Inventory - NPC shops

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#45]
NPC shops with restocks

**Comment by happyDemon** [comment]
How are we going to handle the restock function?
Do it like kitto? letting every item have it's own restock frequency timer

**Comment by Hinton** [comment]
Do we need restock functionality, I don't know how many games use such feature and why.

I'm also slightly unsure if it belongs in the shops? module, or if it would be better to have it as a standalone module as not every game needs it. And should we code it ourselves or let the games that require it implement it?

Well enough about that, giving the items a restock_timer and restock_quantity should give the basic functionality.
We can implement it using 2 different methods, either using cron or calculate it when we load the shop.

Cron would loop over each shop item, compare the last_restocked time with frequency timer and restock if needed.
The other method would be to check if an item should be restocked after we loaded the items in the shop. (Overwrite the load method to check it?)

**Comment by happyDemon** [comment]
instead of looping over every item I think it might be better to query for items which last_restock >= current time + restock frequency. It would save much overhead when an item database grows.

These are NPC shops we're talking about, looking at the fact we're targetting pet games wouldnt a shop restock be vital?

we could add a config so the owner of a game could choose to work with shops that have a as-is stock or shops that restock.

**Comment by Hinton** [comment]
Hmm, would we run that query using cron?

We could have a boolean, use_stock in the items, 0 would give unlimited stock while 1 would use stock that require restocking.

**Comment by happyDemon** [comment]
If we use joins we could reference the needed fields I'm a bit rusty on this but

shop_restock:
id, shop_id, item_id, frequency, last_restock, min_amount, max_amount, max_stock, price

shop_inventory
id, shop_id, item_id, price, stock

$time = time();
SELECT \* FROM shop_restock WHERE last_restock >= $time+frequency

using a cron or a load method wouldn't be a difference.
But we should decide on using crons or load methods(not only for here, but other modules aswel), because I don't see any unity and should we really offer both methods?

I personally favor crons, since it doesn't give the user any extra load when browsing the site.

Are you talking about saving that boolean in a table? because I don't think we should polute the tables with this option, it would be better to store it in a config file.

**Comment by Hinton** [comment]
I was thinking of storing it in the table, as you might want a few items to be unlimited?

I also consider cron to be the best solution in this case as it's only 1 query, + additional update queries. I wonder if it would be possible to use an update query directly, UPDATE shop_restock WHERE last_restock >= $time+frequency SET stock=stock+quantity, last_restock = last_restock+frequency

**Comment by happyDemon** [comment]
I don't think that would be possible, only running one querry, since the restock table is telling us how many items are going into shop_inventory (which would either need an INSERT if the item's not there or an UPDATE if the item's still in stock in the shop).

an unlimited stock of an item could go into shop_inventory with the stock column as -1

**Comment by curtisdelicata** [comment]
I think restocks are needed. We can do it similar to how Kitto does it. The above structure looks good.

**Comment by happyDemon** [comment]
I'm nearly done with the shop script, still need to write the cron for it though.

Should we include price haggling as an option?

**Comment by happyDemon** [comment]
and should we include a buy throttle (e.g. a user can buy a maximum of X items in Y amount of time before a cooldown period of Z seconds is initiated where the user can't buy any items) to give autobuyers a hassle
